<<<<<<< HEAD
###·þÎñ¶Ë¿ÚºÅ
server:
  port: 8000
###·þÎñÃû³Æ
=======
###ï¿½ï¿½ï¿½ï¿½Ë¿Úºï¿½
server:
  port: 8000
###ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
>>>>>>> commit
spring:
  application:
    name: spring-cloud-eureka

eureka:
  instance:
<<<<<<< HEAD
    #×¢²áÖÐÐÄµØÖ·
    hostname: 127.0.0.1
  ###¿Í»§¶Ëµ÷ÓÃµØÖ·
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    ###ÊÇ·ñ½«×Ô¼º×¢²áµ½Eureka·þÎñÖÐ,ÒòÎª¸ÃÓ¦ÓÃ±¾Éí¾ÍÊÇ×¢²áÖÐÐÄ£¬²»ÐèÒªÔÙ×¢²á×Ô¼º£¨¼¯ÈºµÄÊ±ºòÎªtrue£©
    register-with-eureka: false
    ###ÊÇ·ñ´ÓEurekaÖÐ»ñÈ¡×¢²áÐÅÏ¢,ÒòÎª×Ô¼ºÎª×¢²áÖÐÐÄ,²»»áÔÚ¸ÃÓ¦ÓÃÖÐµÄ¼ìË÷·þÎñÐÅÏ¢
    fetch-registry: false
  ### ½ûÓÃ×ÔÎÒ±£»¤Ä£Ê½
=======
    #×¢ï¿½ï¿½ï¿½ï¿½ï¿½Äµï¿½Ö·
    hostname: 127.0.0.1
  ###ï¿½Í»ï¿½ï¿½Ëµï¿½ï¿½Ãµï¿½Ö·
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    ###ï¿½Ç·ï¿½ï¿½Ô¼ï¿½×¢ï¿½áµ½Eurekaï¿½ï¿½ï¿½ï¿½ï¿½ï¿½,ï¿½ï¿½Îªï¿½ï¿½Ó¦ï¿½Ã±ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½×¢ï¿½ï¿½ï¿½ï¿½ï¿½Ä£ï¿½ï¿½ï¿½ï¿½ï¿½Òªï¿½ï¿½×¢ï¿½ï¿½ï¿½Ô¼ï¿½ï¿½ï¿½ï¿½ï¿½Èºï¿½ï¿½Ê±ï¿½ï¿½Îªtrueï¿½ï¿½
    register-with-eureka: false
    ###ï¿½Ç·ï¿½ï¿½Eurekaï¿½Ð»ï¿½È¡×¢ï¿½ï¿½ï¿½ï¿½Ï¢,ï¿½ï¿½Îªï¿½Ô¼ï¿½Îª×¢ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½,ï¿½ï¿½ï¿½ï¿½ï¿½Ú¸ï¿½Ó¦ï¿½ï¿½ï¿½ÐµÄ¼ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ï¢
    fetch-registry: false
  ### ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ò±ï¿½ï¿½ï¿½Ä£Ê½
>>>>>>> commit
  server:
    enableSelfPreservation: false